---
abstract: 'Apply PkgVersion to .pm files with =pod sections'
author:
  - 'Jonathan Swartz <swartz@pobox.com>'
build_requires:
  Dist::Zilla::Plugin::PkgVersion: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200008, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-PkgVersionIfModuleWithPod
no_index:
  directory:
    - lib/Dist/Zilla/Plugin/PkgVersionIfModuleWithPod/t
    - lib/Dist/Zilla/Plugin/PkgVersionIfModuleWithPod/Test
  file:
    - lib/Dist/Zilla/Plugin/PkgVersionIfModuleWithPod/Util.pm
requires:
  Test::More: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Dist-Zilla-Plugin-PkgVersionIfModuleWithPod
  repository: git://github.com/jonswar/perl-dist-zilla-plugin-pkgversionifmodulewithpod.git
version: 0.01
